
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

heating_radiator:
  patches:
    global_0:
      change: 2
      condition:
        - input_boolean.test0
  devices:
    test_room0:
      temperature:
        sensors: input_number.temp0
        target: 20
        max_deviation: 2
      work_interval:
        duration: "00:05:00"
        minimum: "00:00:30"
        maximum: "00:02:00"
        warmup: "00:00:20"
      patches:
        global_0:
        cond_0:
          change: 2
          condition:
            - input_boolean.test1
        cond_1:
          change: -10
          condition:
            - condition: "state"
              entity_id: input_boolean.test2
              state: "on"
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.device0
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.device0

    test_room1:
      temperature:
        sensors: input_number.temp0
        target: 22.1
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.device0
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.device0
#  test_room1:
#    temperature:
#      sensors:
#        - input_number.temp1
#        - input_number.temp2
#      target: 20
#      max_deviation: 3
#    presence_sensors: input_boolean.test3
#    turn_on:
#      - service: input_boolean.turn_on
#        entity_id: input_boolean.device1
#      - service: input_boolean.turn_on
#        entity_id: input_boolean.device2
#    turn_off:
#      service: input_boolean.turn_off
#      entity_id: input_boolean.device1
#  # test_room2:

input_boolean:
  test0:
    initial: off
  test1:
    initial: off
  test2:
    initial: off
  test3:
    initial: off
  device0:
    initial: off
  device1:
    initial: off
  device2:
    initial: off

input_number:
  temp0:
    name: Temp 0
    initial: 22
    min: 0
    max: 35
    step: 0.1
  temp1:
    name: Temp 1
    initial: 22
    min: 0
    max: 35
    step: 0.1
  temp2:
    name: Temp 2
    initial: 22
    min: 0
    max: 35
    step: 0.1
    
logger:
  default: info
  logs:
    custom_components.heating_radiator: debug